PRODUCT_VERSION_MAJOR = 4
PRODUCT_VERSION_MINOR = 0

# Set LINEAGE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifeq ($(CUSTOM_BUILD_TYPE), OFFICIAL)
  LIST = $(shell cat vendor/lineage/nova.devices)
    ifeq ($(filter $(CUSTOM_BUILD), $(LIST)), $(CUSTOM_BUILD))
      CUSTOM_BUILD_TYPE := OFFICIAL
    else
      CUSTOM_BUILD_TYPE := UNOFFICIAL
    endif
endif

ifeq ($(LINEAGE_VERSION_APPEND_TIME_OF_DAY),true)
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d%H%M%S)
else
    LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Custom Version
CUSTOM_BUILD_TYPE ?= COMMUNITY
CUSTOM_BUILD := Ignite
CUSTOM_BUILD_VARIANT ?= VANILLA

# Gapps
ifeq ($(WITH_GAPPS),true)
CUSTOM_BUILD_VARIANT := GAPPS
else
CUSTOM_BUILD_VARIANT := VANILLA
endif

# novaline Version
NOVA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

LINEAGE_VERSION_SUFFIX := $(CUSTOM_BUILD_TYPE)-$(CUSTOM_BUILD_VARIANT)-$(CUSTOM_BUILD)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)

# novaline props
PRODUCT_SYSTEM_PROPERTIES += \
    ro.nova.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# LineageOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.nova.version=$(LINEAGE_VERSION) \
    ro.nova.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.nova.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.nova.releasetype=$(LINEAGE_BUILDTYPE)
